[package]
name = "flamingo"
version = "0.1.0"
edition = "2024"

[dependencies]
ansi-to-tui = "8.0.1"
better-panic = "0.3.0"
clap = { version = "4.6.1", features = ["derive", "env", "wrap_help", "cargo"] }
dirs = "6.0.0"
heh = "0.6.3"
itertools = "0.15.0"
log = "0.4.33"
pretty_assertions = "1.4.1"
ratatui = "0.30.2"
ratatui-explorer = "0.3.0"
regex = "1.12.4"
rstest = "0.26.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
simplelog = "0.12.2"
tempdir = "0.3.7"
termbg = "0.6.2"
thiserror = "2.0.18"
toml = "1.1.2"
tui-big-text = "0.8.8"
tui-input = "0.15.3"
tui-popup = "0.7.6"
tui-syntax-highlight = "0.2.0"
unicode-width = "0.2.2"
url = "2.5.8"
webbrowser = "1.2.1"
